env:
  global:
    - secure: YWthcycNNxuL2tN3kEmKvA/w2yAAhVnWsXoP404VOm/NHIQsBHSSceRlDSM6lwcq+Bj7w6yJc4LKZs0ulW/mWdgkREPsOOWeg8oEmPny6I6OwxAvI4eIuGmVh7KyHgekKGUFgxj3NvM/AsErTmm2YaDzc+2asKU/S2i9FgPzgtkTH1PqzKeF3AcNpqEtWjFMUBGFT0DkytEzv6OQEQYK3NOHcwjYtQP60PwC6zYdGivdtdCeecZLTpvy4wjWPPtSUJrt2v0F/L5eERnPAeHJMy1waUAj3mlz3xkif+ixMU/UzoTDlFvyvBL4tq2BnhDhw1BldtgHIeHyoMtrgmJvJNTmZbepPC8zMI24v6A3jZ6xuDqRH2Y4eOnk3TT8VDrgOlwUq7B8cSm+A2F7Du/ocDaFjusVmeFIDSWdO+BTqO8f7Kc58ycSSbpO2nRY2XA6mKGmdpOMJkEvH7c6IEHubEHGF5s0ktih3Ldae1RMOi2kH6QOd7rwhld5dctmmsQDARHcOcwThZRdKap4X9qHeE7PaPEcAYqwkQzuODSeyY9CJUwVCo5V94SuJbXEOn7Syy7Fut91oQS3dsBszimBzTBiZvwNCoQTEVT67MHsL3N2S46nKMwa0OdIYSj4tsamF0gfrO0O9+uvNB8ZOLTELpeIp5oBs90+iO6IurwlJg0=
    - DUMPS_VERSION=dumps_1
matrix:
  include:
    - os: linux
      dist: trusty
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - gcc-7
            - g++-7
            - gcc-multilib
            - g++-multilib
            - gcc-7-multilib
            - g++-7-multilib
            - clang-6.0
            - gdb
            - libc++-dev
      script:
        - echo 0 | sudo tee /proc/sys/kernel/randomize_va_space
        - g++-7 -v
        - clang++ -v
        - mkdir Source/NativeDumpTest/bin
        - g++-7 Source/NativeDumpTest/NativeDumpTest.cpp -o Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.gcc -std=c++11 -g -static-libgcc -static-libstdc++
        - g++-7 -m32 Source/NativeDumpTest/NativeDumpTest.cpp -o Source/NativeDumpTest/bin/NativeDumpTest.linux.x86.gcc -std=c++11 -g -static-libgcc -static-libstdc++
        - clang++ Source/NativeDumpTest/NativeDumpTest.cpp -o Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.clang -stdlib=libc++ -std=c++11 -g -static-libgcc -static-libstdc++ -pthread -fno-limit-debug-info
        - gdb --batch Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.gcc -ex 'r' -ex 'generate-core-file Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.gcc.coredump' -ex 'quit'
        - gdb --batch Source/NativeDumpTest/bin/NativeDumpTest.linux.x86.gcc -ex 'r' -ex 'generate-core-file Source/NativeDumpTest/bin/NativeDumpTest.linux.x86.gcc.coredump' -ex 'quit'
        - gdb --batch Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.clang -ex 'r' -ex 'generate-core-file Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.clang.coredump' -ex 'quit'
        - g++-7 Source/NativeDumpTest/NativeDumpTest.cpp -o Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.gcc.nortti -std=c++11 -g -fno-rtti -static-libgcc -static-libstdc++
        - g++-7 -m32 Source/NativeDumpTest/NativeDumpTest.cpp -o Source/NativeDumpTest/bin/NativeDumpTest.linux.x86.gcc.nortti -std=c++11 -g -fno-rtti -static-libgcc -static-libstdc++
        - clang++ Source/NativeDumpTest/NativeDumpTest.cpp -o Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.clang.nortti -stdlib=libc++ -std=c++11 -g -fno-rtti -static-libgcc -static-libstdc++ -pthread -fno-limit-debug-info
        - gdb --batch Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.gcc.nortti -ex 'r' -ex 'generate-core-file Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.gcc.nortti.coredump' -ex 'quit'
        - gdb --batch Source/NativeDumpTest/bin/NativeDumpTest.linux.x86.gcc.nortti -ex 'r' -ex 'generate-core-file Source/NativeDumpTest/bin/NativeDumpTest.linux.x86.gcc.nortti.coredump' -ex 'quit'
        - gdb --batch Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.clang.nortti -ex 'r' -ex 'generate-core-file Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.clang.nortti.coredump' -ex 'quit'
        - ls Source/NativeDumpTest/bin/ -la
        - cd Source/NativeDumpTest/bin;zip NativeDumpTest.linux.zip * -9;cd ../../../
        - curl -T Source/NativeDumpTest/bin/NativeDumpTest.linux.zip -uciupload:$ARTIFACTS_PASSWORD https://sharpdebug.jfrog.io/sharpdebug/generic-local/$DUMPS_VERSION/NativeDumpTest.linux.zip?override=1
        - mkdir Source/Cpp17/bin
        - g++-7 Source/Cpp17/Cpp17.cpp -o Source/Cpp17/bin/cpp17.linux.x64.gcc -std=c++17 -g -static-libgcc -static-libstdc++
        - g++-7 -m32 Source/Cpp17/Cpp17.cpp -o Source/Cpp17/bin/cpp17.linux.x86.gcc -std=c++17 -g -static-libgcc -static-libstdc++
        - clang++ Source/Cpp17/Cpp17.cpp -o Source/Cpp17/bin/cpp17.linux.x64.clang -stdlib=libc++ -std=c++17 -g -static-libgcc -static-libstdc++ -pthread -fno-limit-debug-info
        - gdb --batch Source/Cpp17/bin/cpp17.linux.x64.gcc -ex 'r' -ex 'generate-core-file Source/Cpp17/bin/cpp17.linux.x64.gcc.coredump' -ex 'quit'
        - gdb --batch Source/Cpp17/bin/cpp17.linux.x86.gcc -ex 'r' -ex 'generate-core-file Source/Cpp17/bin/cpp17.linux.x86.gcc.coredump' -ex 'quit'
        - gdb --batch Source/Cpp17/bin/cpp17.linux.x64.clang -ex 'r' -ex 'generate-core-file Source/Cpp17/bin/cpp17.linux.x64.clang.coredump' -ex 'quit'
        - g++-7 Source/Cpp17/Cpp17.cpp -o Source/Cpp17/bin/cpp17.linux.x64.gcc.nortti -std=c++17 -g -fno-rtti -static-libgcc -static-libstdc++
        - g++-7 -m32 Source/Cpp17/Cpp17.cpp -o Source/Cpp17/bin/cpp17.linux.x86.gcc.nortti -std=c++17 -g -fno-rtti -static-libgcc -static-libstdc++
        - clang++ Source/Cpp17/Cpp17.cpp -o Source/Cpp17/bin/cpp17.linux.x64.clang.nortti -stdlib=libc++ -std=c++17 -g -fno-rtti -static-libgcc -static-libstdc++ -pthread -fno-limit-debug-info
        - gdb --batch Source/Cpp17/bin/cpp17.linux.x64.gcc.nortti -ex 'r' -ex 'generate-core-file Source/Cpp17/bin/cpp17.linux.x64.gcc.nortti.coredump' -ex 'quit'
        - gdb --batch Source/Cpp17/bin/cpp17.linux.x86.gcc.nortti -ex 'r' -ex 'generate-core-file Source/Cpp17/bin/cpp17.linux.x86.gcc.nortti.coredump' -ex 'quit'
        - gdb --batch Source/Cpp17/bin/cpp17.linux.x64.clang.nortti -ex 'r' -ex 'generate-core-file Source/Cpp17/bin/cpp17.linux.x64.clang.nortti.coredump' -ex 'quit'
        - ls Source/Cpp17/bin/ -la
        - cd Source/Cpp17/bin;zip Cpp17.linux.zip * -9;cd ../../../
        - curl -T Source/Cpp17/bin/Cpp17.linux.zip -uciupload:$ARTIFACTS_PASSWORD https://sharpdebug.jfrog.io/sharpdebug/generic-local/$DUMPS_VERSION/Cpp17.linux.zip?override=1
