env:
  global:
    - secure: YWthcycNNxuL2tN3kEmKvA/w2yAAhVnWsXoP404VOm/NHIQsBHSSceRlDSM6lwcq+Bj7w6yJc4LKZs0ulW/mWdgkREPsOOWeg8oEmPny6I6OwxAvI4eIuGmVh7KyHgekKGUFgxj3NvM/AsErTmm2YaDzc+2asKU/S2i9FgPzgtkTH1PqzKeF3AcNpqEtWjFMUBGFT0DkytEzv6OQEQYK3NOHcwjYtQP60PwC6zYdGivdtdCeecZLTpvy4wjWPPtSUJrt2v0F/L5eERnPAeHJMy1waUAj3mlz3xkif+ixMU/UzoTDlFvyvBL4tq2BnhDhw1BldtgHIeHyoMtrgmJvJNTmZbepPC8zMI24v6A3jZ6xuDqRH2Y4eOnk3TT8VDrgOlwUq7B8cSm+A2F7Du/ocDaFjusVmeFIDSWdO+BTqO8f7Kc58ycSSbpO2nRY2XA6mKGmdpOMJkEvH7c6IEHubEHGF5s0ktih3Ldae1RMOi2kH6QOd7rwhld5dctmmsQDARHcOcwThZRdKap4X9qHeE7PaPEcAYqwkQzuODSeyY9CJUwVCo5V94SuJbXEOn7Syy7Fut91oQS3dsBszimBzTBiZvwNCoQTEVT67MHsL3N2S46nKMwa0OdIYSj4tsamF0gfrO0O9+uvNB8ZOLTELpeIp5oBs90+iO6IurwlJg0=
    - DUMPS_VERSION=dumps_3
matrix:
  include:
    - os: linux
      dist: trusty
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
            - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
              key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
          packages:
            - gcc-8
            - g++-8
            - gcc-multilib
            - g++-multilib
            - gcc-8-multilib
            - g++-8-multilib
            - clang-7
            - gdb
            - libc++-7-dev
            - libc++abi-7-dev
            - dotnet-sdk-2.1.4
      script:
        - echo 0 | sudo tee /proc/sys/kernel/randomize_va_space
        - g++-8 -v
        - clang++-7 -v
        - mkdir Source/NativeDumpTest/bin
        - g++-8 Source/NativeDumpTest/NativeDumpTest.cpp -o Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.gcc -std=c++11 -g -static-libgcc -static-libstdc++
        - g++-8 -m32 Source/NativeDumpTest/NativeDumpTest.cpp -o Source/NativeDumpTest/bin/NativeDumpTest.linux.x86.gcc -std=c++11 -g -static-libgcc -static-libstdc++
        - clang++-7 Source/NativeDumpTest/NativeDumpTest.cpp -o Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.clang -stdlib=libc++ -std=c++11 -g -static-libgcc -static-libstdc++ -pthread -fno-limit-debug-info -lc++abi -lsupc++
        - gdb --batch Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.gcc -ex 'r' -ex 'generate-core-file Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.gcc.coredump' -ex 'quit'
        - gdb --batch Source/NativeDumpTest/bin/NativeDumpTest.linux.x86.gcc -ex 'r' -ex 'generate-core-file Source/NativeDumpTest/bin/NativeDumpTest.linux.x86.gcc.coredump' -ex 'quit'
        - gdb --batch Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.clang -ex 'r' -ex 'generate-core-file Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.clang.coredump' -ex 'quit'
        - g++-8 Source/NativeDumpTest/NativeDumpTest.cpp -o Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.gcc.nortti -std=c++11 -g -fno-rtti -static-libgcc -static-libstdc++
        - g++-8 -m32 Source/NativeDumpTest/NativeDumpTest.cpp -o Source/NativeDumpTest/bin/NativeDumpTest.linux.x86.gcc.nortti -std=c++11 -g -fno-rtti -static-libgcc -static-libstdc++
        - clang++-7 Source/NativeDumpTest/NativeDumpTest.cpp -o Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.clang.nortti -stdlib=libc++ -std=c++11 -g -fno-rtti -static-libgcc -static-libstdc++ -pthread -fno-limit-debug-info -lc++abi -lsupc++
        - gdb --batch Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.gcc.nortti -ex 'r' -ex 'generate-core-file Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.gcc.nortti.coredump' -ex 'quit'
        - gdb --batch Source/NativeDumpTest/bin/NativeDumpTest.linux.x86.gcc.nortti -ex 'r' -ex 'generate-core-file Source/NativeDumpTest/bin/NativeDumpTest.linux.x86.gcc.nortti.coredump' -ex 'quit'
        - gdb --batch Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.clang.nortti -ex 'r' -ex 'generate-core-file Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.clang.nortti.coredump' -ex 'quit'
        - ls Source/NativeDumpTest/bin/ -la
        - cd Source/NativeDumpTest/bin;zip NativeDumpTest.linux.zip * -9;cd ../../../
        - curl -T Source/NativeDumpTest/bin/NativeDumpTest.linux.zip -uciupload:$ARTIFACTS_PASSWORD https://sharpdebug.jfrog.io/sharpdebug/generic-local/$DUMPS_VERSION/NativeDumpTest.linux.zip?override=1
        - mkdir Source/Cpp17/bin
        - g++-8 Source/Cpp17/Cpp17.cpp -o Source/Cpp17/bin/cpp17.linux.x64.gcc -std=c++17 -g -static-libgcc -static-libstdc++ -lstdc++fs
        - g++-8 -m32 Source/Cpp17/Cpp17.cpp -o Source/Cpp17/bin/cpp17.linux.x86.gcc -std=c++17 -g -static-libgcc -static-libstdc++ -lstdc++fs
        - clang++-7 Source/Cpp17/Cpp17.cpp -o Source/Cpp17/bin/cpp17.linux.x64.clang -stdlib=libc++ -std=c++17 -g -static-libgcc -static-libstdc++ -pthread -fno-limit-debug-info -lc++fs -lc++abi -lsupc++
        - gdb --batch Source/Cpp17/bin/cpp17.linux.x64.gcc -ex 'r' -ex 'generate-core-file Source/Cpp17/bin/cpp17.linux.x64.gcc.coredump' -ex 'quit'
        - gdb --batch Source/Cpp17/bin/cpp17.linux.x86.gcc -ex 'r' -ex 'generate-core-file Source/Cpp17/bin/cpp17.linux.x86.gcc.coredump' -ex 'quit'
        - gdb --batch Source/Cpp17/bin/cpp17.linux.x64.clang -ex 'r' -ex 'generate-core-file Source/Cpp17/bin/cpp17.linux.x64.clang.coredump' -ex 'quit'
        - g++-8 Source/Cpp17/Cpp17.cpp -o Source/Cpp17/bin/cpp17.linux.x64.gcc.nortti -std=c++17 -g -fno-rtti -static-libgcc -static-libstdc++ -lstdc++fs
        - g++-8 -m32 Source/Cpp17/Cpp17.cpp -o Source/Cpp17/bin/cpp17.linux.x86.gcc.nortti -std=c++17 -g -fno-rtti -static-libgcc -static-libstdc++ -lstdc++fs
        - clang++-7 Source/Cpp17/Cpp17.cpp -o Source/Cpp17/bin/cpp17.linux.x64.clang.nortti -stdlib=libc++ -std=c++17 -g -fno-rtti -static-libgcc -static-libstdc++ -pthread -fno-limit-debug-info -lc++fs -lc++abi -lsupc++
        - gdb --batch Source/Cpp17/bin/cpp17.linux.x64.gcc.nortti -ex 'r' -ex 'generate-core-file Source/Cpp17/bin/cpp17.linux.x64.gcc.nortti.coredump' -ex 'quit'
        - gdb --batch Source/Cpp17/bin/cpp17.linux.x86.gcc.nortti -ex 'r' -ex 'generate-core-file Source/Cpp17/bin/cpp17.linux.x86.gcc.nortti.coredump' -ex 'quit'
        - gdb --batch Source/Cpp17/bin/cpp17.linux.x64.clang.nortti -ex 'r' -ex 'generate-core-file Source/Cpp17/bin/cpp17.linux.x64.clang.nortti.coredump' -ex 'quit'
        - ls Source/Cpp17/bin/ -la
        - cd Source/Cpp17/bin;zip Cpp17.linux.zip * -9;cd ../../../
        - curl -T Source/Cpp17/bin/Cpp17.linux.zip -uciupload:$ARTIFACTS_PASSWORD https://sharpdebug.jfrog.io/sharpdebug/generic-local/$DUMPS_VERSION/Cpp17.linux.zip?override=1
        - cd Source/Clr; dotnet build; cd ../../
        - mkdir Source/Clr/bin
        - cp Source/Clr/AppDomains/bin/Debug/netcoreapp2.0/AppDomains.dll Source/Clr/bin/
        - cp Source/Clr/LocalVariables/bin/Debug/netcoreapp2.0/LocalVariables.dll Source/Clr/bin/
        - cp Source/Clr/NestedException/bin/Debug/netcoreapp2.0/NestedException.dll Source/Clr/bin/
        - cp Source/Clr/SharedLibrary/bin/Debug/netstandard2.0/SharedLibrary.dll Source/Clr/bin/
        - cp Source/Clr/Types/bin/Debug/netcoreapp2.0/Types.dll Source/Clr/bin/
        - gdb --batch 'dotnet' -ex 'r Source/Clr/AppDomains/bin/Debug/netcoreapp2.0/AppDomains.dll' -ex 'generate-core-file Source/Clr/bin/AppDomains.linux.coredump' -ex 'quit'
        - gdb --batch 'dotnet' -ex 'r Source/Clr/LocalVariables/bin/Debug/netcoreapp2.0/LocalVariables.dll' -ex 'generate-core-file Source/Clr/bin/LocalVariables.linux.coredump' -ex 'quit'
        - gdb --batch 'dotnet' -ex 'r Source/Clr/NestedException/bin/Debug/netcoreapp2.0/NestedException.dll' -ex 'generate-core-file Source/Clr/bin/NestedException.linux.coredump' -ex 'quit'
        - gdb --batch 'dotnet' -ex 'r Source/Clr/Types/bin/Debug/netcoreapp2.0/Types.dll' -ex 'generate-core-file Source/Clr/bin/Types.linux.coredump' -ex 'quit'
