version: 1.0.{build}

image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  DUMPS_VERSION: dumps_1
  PROJECT_ROOT: C:\projects\windbgcs-dumps
  DUMPER: $(PROJECT_ROOT)\Source\ExceptionDumper\bin\Debug\net461\ExceptionDumper.exe
  DUMPER32: $(PROJECT_ROOT)\Source\ExceptionDumper32\bin\Debug\net461\ExceptionDumper32.exe
  ARTIFACTS_USERNAME: ciupload
  ARTIFACTS_PASSWORD:
    secure: oTegwrEw7mLsNdGljbzQonwCm0UupJ7oRK/jI3Mosrk=

build_script:
  - ps: |-
        if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2013") {
            cd Source\ExceptionDumper32
            dotnet restore
            dotnet msbuild
            cd ..\..\
        }
  - cmd: IF NOT EXIST %DUMPER% ( SET DUMPER=%PROJECT_ROOT%\bin\ExceptionDumper.exe )
  - cmd: ECHO %DUMPER%
  - cmd: IF NOT EXIST %DUMPER32% ( SET DUMPER32=%PROJECT_ROOT%\bin\ExceptionDumper32.exe )
  - cmd: ECHO %DUMPER32%
  - cmd: msbuild Source\NativeDumpTest\NativeDumpTest.x64.vcxproj /p:Configuration=Debug;Platform=x64 /verbosity:minimal /nologo
  - ps: |-
        if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2017") {
            msbuild Source\NativeDumpTest\NativeDumpTest.x64.Release.vcxproj /p:Configuration=Release;Platform=x64 /verbosity:minimal /nologo
            msbuild Source\NativeDumpTest\NativeDumpTest.x86.vcxproj /p:Configuration=Debug;Platform=Win32 /verbosity:minimal /nologo
            msbuild Source\NativeDumpTest\NativeDumpTest.x86.Release.vcxproj /p:Configuration=Release;Platform=Win32 /verbosity:minimal /nologo
        }
  - cmd: SET gccpath=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin
  - cmd: SET ORIGINAL_PATH=%PATH%
  - cmd: SET PATH=%gccpath%;%ORIGINAL_PATH%
  - cmd: IF EXIST %gccpath% ( %gccpath%\g++ %PROJECT_ROOT%\Source\NativeDumpTest\NativeDumpTest.cpp -o %PROJECT_ROOT%\Source\NativeDumpTest\bin\NativeDumpTest.x64.gcc.exe -std=c++11 -g )
  - cmd: IF EXIST %gccpath% ( %DUMPER% -a %PROJECT_ROOT%\Source\NativeDumpTest\bin\NativeDumpTest.x64.gcc.exe -d %PROJECT_ROOT%\Source\NativeDumpTest\bin\NativeDumpTest.x64.gcc.mdmp )
  - cmd: SET gccpath=C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin
  - cmd: SET PATH=%gccpath%;%ORIGINAL_PATH%
  - cmd: IF EXIST %gccpath% ( %gccpath%\g++ %PROJECT_ROOT%\Source\NativeDumpTest\NativeDumpTest.cpp -o %PROJECT_ROOT%\Source\NativeDumpTest\bin\NativeDumpTest.gcc.exe -std=c++11 -g )
  - cmd: IF EXIST %gccpath% ( %DUMPER32% -a %PROJECT_ROOT%\Source\NativeDumpTest\bin\NativeDumpTest.gcc.exe -d %PROJECT_ROOT%\Source\NativeDumpTest\bin\NativeDumpTest.gcc.mdmp )
  - cmd: IF EXIST %gccpath% ( 7z a %PROJECT_ROOT%\NativeDumpTest.mingw.zip %PROJECT_ROOT%\Source\NativeDumpTest\bin\* )
  - ps: |-
        if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2017") {
            msbuild Source\Cpp17\Cpp17.vcxproj /p:Configuration=Debug;Platform=x64 /verbosity:minimal /nologo
            msbuild Source\Cpp17\Cpp17.vcxproj /p:Configuration=Release;Platform=x64 /verbosity:minimal /nologo
            msbuild Source\Cpp17\Cpp17.vcxproj /p:Configuration=Debug;Platform=Win32 /verbosity:minimal /nologo
            msbuild Source\Cpp17\Cpp17.vcxproj /p:Configuration=Release;Platform=Win32 /verbosity:minimal /nologo
        }
  - ps: |-
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;
        $webClient = New-Object System.Net.WebClient;
        $webClient.Credentials = new-object System.Net.NetworkCredential($env:ARTIFACTS_USERNAME, $env:ARTIFACTS_PASSWORD);
        if (Test-Path NativeDumpTest.mingw.zip) {
            $filename = "NativeDumpTest.mingw.zip";
            $url = "https://sharpdebug.jfrog.io/sharpdebug/generic-local/${env:DUMPS_VERSION}/${filename}?override=1";
            $webClient.UploadData($url, "PUT", [System.IO.File]::ReadAllBytes($filename));
        }

artifacts:
  - path: '**\bin\*.exe'
  - path: '**\bin\*.pdb'
  - path: '**\bin\*.*dmp'
  - path: '**\*.zip'
