version: 1.0.{build}

image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

build_script:
  - IF NOT "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2013" ( cd Source\ExceptionDumper32 )
  - IF NOT "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2013" ( dotnet restore )
  - IF NOT "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2013" ( dotnet msbuild )
  - IF NOT "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2013" ( cd ..\..\ )
  - SET project_root=C:\projects\windbgcs-dumps
  - SET DUMPER=%project_root%\Source\ExceptionDumper\bin\Debug\net461\ExceptionDumper.exe
  - IF NOT EXIST %DUMPER% ( SET DUMPER=%project_root%\bin\ExceptionDumper.exe )
  - ECHO %DUMPER%
  - SET DUMPER32=%project_root%\Source\ExceptionDumper32\bin\Debug\net461\ExceptionDumper32.exe
  - IF NOT EXIST %DUMPER32% ( SET DUMPER32=%project_root%\bin\ExceptionDumper32.exe )
  - ECHO %DUMPER32%
  - msbuild Source\NativeDumpTest\NativeDumpTest.x64.vcxproj /p:Configuration=Debug;Platform=x64 /verbosity:minimal /nologo
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( msbuild Source\NativeDumpTest\NativeDumpTest.x64.Release.vcxproj /p:Configuration=Release;Platform=x64 /verbosity:minimal /nologo )
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( msbuild Source\NativeDumpTest\NativeDumpTest.x86.vcxproj /p:Configuration=Debug;Platform=Win32 /verbosity:minimal /nologo )
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( msbuild Source\NativeDumpTest\NativeDumpTest.x86.Release.vcxproj /p:Configuration=Release;Platform=Win32 /verbosity:minimal /nologo )
  - SET gccpath=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin
  - SET ORIGINAL_PATH=%PATH%
  - SET PATH=%gccpath%;%ORIGINAL_PATH%
  - IF EXIST %gccpath% ( %gccpath%\g++ %project_root%\Source\NativeDumpTest\NativeDumpTest.cpp -o %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.x64.gcc.exe -std=c++11 -g )
  - IF EXIST %gccpath% ( %DUMPER% -a %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.x64.gcc.exe -d %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.x64.gcc.mdmp )
  - SET gccpath=C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin
  - SET PATH=%gccpath%;%ORIGINAL_PATH%
  - IF EXIST %gccpath% ( %gccpath%\g++ %project_root%\Source\NativeDumpTest\NativeDumpTest.cpp -o %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.gcc.exe -std=c++11 -g )
  - IF EXIST %gccpath% ( %DUMPER32% -a %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.gcc.exe -d %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.gcc.mdmp )
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( msbuild Source\Cpp17\Cpp17.vcxproj /p:Configuration=Debug;Platform=x64 /verbosity:minimal /nologo )
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( msbuild Source\Cpp17\Cpp17.vcxproj /p:Configuration=Release;Platform=x64 /verbosity:minimal /nologo )
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( msbuild Source\Cpp17\Cpp17.vcxproj /p:Configuration=Debug;Platform=Win32 /verbosity:minimal /nologo )
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( msbuild Source\Cpp17\Cpp17.vcxproj /p:Configuration=Release;Platform=Win32 /verbosity:minimal /nologo )

artifacts:
  - path: '**\bin\*.exe'
  - path: '**\bin\*.pdb'
  - path: '**\bin\*.*dmp'

deploy:
  - provider: BinTray
    username: southpolenator
    api_key:
      secure: ppEFGKPnh2vKBMCVFei2oBVFZ7m3pKtSP41wWFuwyNZ3AkuYgV2rTiZY07kwnifO
    subject: southpolenator
    repo: WinDbgCs_dumps
    version: 1.0
    package: NativeDumpTest.1
    publish: true
    override: true
    explode: true
