version: 1.0.{build}

image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  DUMPS_VERSION: dumps_3
  PROJECT_ROOT: C:\projects\windbgcs-dumps
  DUMPER: $(PROJECT_ROOT)\Source\ExceptionDumper\bin\Debug\net461\ExceptionDumper.exe
  DUMPER32: $(PROJECT_ROOT)\Source\ExceptionDumper32\bin\Debug\net461\ExceptionDumper32.exe
  CORFLAGS: corflags
  ARTIFACTS_USERNAME: ciupload
  ARTIFACTS_PASSWORD:
    secure: oTegwrEw7mLsNdGljbzQonwCm0UupJ7oRK/jI3Mosrk=

build_script:
  - ps: |-
        if (-not ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2013")) {
            cd Source\ExceptionDumper32
            dotnet.exe restore
            dotnet.exe msbuild
            cd ..\..\
        }
  - cmd: IF NOT EXIST %DUMPER% ( SET DUMPER=%PROJECT_ROOT%\bin\ExceptionDumper.exe )
  - cmd: ECHO %DUMPER%
  - cmd: IF NOT EXIST %DUMPER32% ( SET DUMPER32=%PROJECT_ROOT%\bin\ExceptionDumper32.exe )
  - cmd: ECHO %DUMPER32%
  - cmd: msbuild Source\NativeDumpTest\NativeDumpTest.x64.vcxproj /p:Configuration=Debug;Platform=x64 /verbosity:minimal /nologo
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( msbuild Source\NativeDumpTest\NativeDumpTest.x64.Release.vcxproj /p:Configuration=Release;Platform=x64 /verbosity:minimal /nologo )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( msbuild Source\NativeDumpTest\NativeDumpTest.x86.vcxproj /p:Configuration=Debug;Platform=Win32 /verbosity:minimal /nologo )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( msbuild Source\NativeDumpTest\NativeDumpTest.x86.Release.vcxproj /p:Configuration=Release;Platform=Win32 /verbosity:minimal /nologo )
  - cmd: SET gccpath=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin
  - cmd: SET ORIGINAL_PATH=%PATH%
  - cmd: SET PATH=%gccpath%;%ORIGINAL_PATH%
  - cmd: IF EXIST %gccpath% ( %gccpath%\g++ %PROJECT_ROOT%\Source\NativeDumpTest\NativeDumpTest.cpp -o %PROJECT_ROOT%\Source\NativeDumpTest\bin\NativeDumpTest.x64.gcc.exe -std=c++11 -g )
  - cmd: IF EXIST %gccpath% ( %DUMPER% -a %PROJECT_ROOT%\Source\NativeDumpTest\bin\NativeDumpTest.x64.gcc.exe -d %PROJECT_ROOT%\Source\NativeDumpTest\bin\NativeDumpTest.x64.gcc.mdmp )
  - cmd: SET gccpath=C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin
  - cmd: SET PATH=%gccpath%;%ORIGINAL_PATH%
  - cmd: IF EXIST %gccpath% ( %gccpath%\g++ %PROJECT_ROOT%\Source\NativeDumpTest\NativeDumpTest.cpp -o %PROJECT_ROOT%\Source\NativeDumpTest\bin\NativeDumpTest.gcc.exe -std=c++11 -g )
  - cmd: IF EXIST %gccpath% ( %DUMPER32% -a %PROJECT_ROOT%\Source\NativeDumpTest\bin\NativeDumpTest.gcc.exe -d %PROJECT_ROOT%\Source\NativeDumpTest\bin\NativeDumpTest.gcc.mdmp )
  - cmd: dir %PROJECT_ROOT%\Source\NativeDumpTest\bin\*
  - cmd: IF EXIST %gccpath% ( 7z a %PROJECT_ROOT%\NativeDumpTest.mingw.zip %PROJECT_ROOT%\Source\NativeDumpTest\bin\*gcc*.exe %PROJECT_ROOT%\Source\NativeDumpTest\bin\*gcc*.mdmp )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2013" ( 7z a %PROJECT_ROOT%\NativeDumpTest.VS2013.zip %PROJECT_ROOT%\Source\NativeDumpTest\bin\*VS2013*.exe %PROJECT_ROOT%\Source\NativeDumpTest\bin\*VS2013*.mdmp %PROJECT_ROOT%\Source\NativeDumpTest\bin\*VS2013*.pdb )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" ( 7z a %PROJECT_ROOT%\NativeDumpTest.VS2015.zip %PROJECT_ROOT%\Source\NativeDumpTest\bin\*VS2015*.exe %PROJECT_ROOT%\Source\NativeDumpTest\bin\*VS2015*.mdmp %PROJECT_ROOT%\Source\NativeDumpTest\bin\*VS2015*.pdb )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( 7z a %PROJECT_ROOT%\NativeDumpTest.VS2017.zip %PROJECT_ROOT%\Source\NativeDumpTest\bin\*.exe %PROJECT_ROOT%\Source\NativeDumpTest\bin\*.mdmp %PROJECT_ROOT%\Source\NativeDumpTest\bin\*.pdb )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( msbuild Source\Cpp17\Cpp17.vcxproj /p:Configuration=Debug;Platform=x64 /verbosity:minimal /nologo )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( msbuild Source\Cpp17\Cpp17.vcxproj /p:Configuration=Release;Platform=x64 /verbosity:minimal /nologo )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( msbuild Source\Cpp17\Cpp17.vcxproj /p:Configuration=Debug;Platform=Win32 /verbosity:minimal /nologo )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( msbuild Source\Cpp17\Cpp17.vcxproj /p:Configuration=Release;Platform=Win32 /verbosity:minimal /nologo )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( dir %PROJECT_ROOT%\Source\Cpp17\bin\* )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( 7z a %PROJECT_ROOT%\Cpp17.VS2017.zip %PROJECT_ROOT%\Source\Cpp17\bin\*.exe %PROJECT_ROOT%\Source\Cpp17\bin\*.mdmp %PROJECT_ROOT%\Source\Cpp17\bin\*.pdb )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( dotnet build %PROJECT_ROOT%\Source\Clr\Clr.sln )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( md %PROJECT_ROOT%\Source\Clr\Core )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( copy %PROJECT_ROOT%\Source\Clr\AppDomains\bin\Debug\netcoreapp2.0\AppDomains.* %PROJECT_ROOT%\Source\Clr\Core )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( copy %PROJECT_ROOT%\Source\Clr\LocalVariables\bin\Debug\netcoreapp2.0\LocalVariables.* %PROJECT_ROOT%\Source\Clr\Core )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( copy %PROJECT_ROOT%\Source\Clr\NestedException\bin\Debug\netcoreapp2.0\NestedException.* %PROJECT_ROOT%\Source\Clr\Core )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( copy %PROJECT_ROOT%\Source\Clr\SharedLibrary\bin\Debug\netstandard2.0\SharedLibrary.* %PROJECT_ROOT%\Source\Clr\Core )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( copy %PROJECT_ROOT%\Source\Clr\Types\bin\Debug\netcoreapp2.0\Types.* %PROJECT_ROOT%\Source\Clr\Core )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %DUMPER% -a "dotnet %PROJECT_ROOT%\Source\Clr\AppDomains\bin\Debug\netcoreapp2.0\AppDomains.dll" -d %PROJECT_ROOT%\Source\Clr\Core\AppDomains.Core.mdmp )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %DUMPER% -a "dotnet %PROJECT_ROOT%\Source\Clr\LocalVariables\bin\Debug\netcoreapp2.0\LocalVariables.dll" -d %PROJECT_ROOT%\Source\Clr\Core\LocalVariables.Core.mdmp )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %DUMPER% -a "dotnet %PROJECT_ROOT%\Source\Clr\NestedException\bin\Debug\netcoreapp2.0\NestedException.dll" -d %PROJECT_ROOT%\Source\Clr\Core\NestedException.Core.mdmp )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %DUMPER% -a "dotnet %PROJECT_ROOT%\Source\Clr\Types\bin\Debug\netcoreapp2.0\Types.dll" -d %PROJECT_ROOT%\Source\Clr\Core\Types.Core.mdmp )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( 7z a %PROJECT_ROOT%\Clr.Windows.Core.zip %PROJECT_ROOT%\Source\Clr\Core\*.* )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( md %PROJECT_ROOT%\Source\Clr\Framework.x64 )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( copy %PROJECT_ROOT%\Source\Clr\AppDomains\bin\Debug\net461\AppDomains.* %PROJECT_ROOT%\Source\Clr\Framework.x64 )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( copy %PROJECT_ROOT%\Source\Clr\LocalVariables\bin\Debug\net461\LocalVariables.* %PROJECT_ROOT%\Source\Clr\Framework.x64 )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( copy %PROJECT_ROOT%\Source\Clr\NestedException\bin\Debug\net461\NestedException.* %PROJECT_ROOT%\Source\Clr\Framework.x64 )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( copy %PROJECT_ROOT%\Source\Clr\SharedLibrary\bin\Debug\netstandard2.0\SharedLibrary.* %PROJECT_ROOT%\Source\Clr\Framework.x64 )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( copy %PROJECT_ROOT%\Source\Clr\Types\bin\Debug\net461\Types.* %PROJECT_ROOT%\Source\Clr\Framework.x64 )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %DUMPER% -a "%PROJECT_ROOT%\Source\Clr\AppDomains\bin\Debug\net461\AppDomains.exe" -d %PROJECT_ROOT%\Source\Clr\Framework.x64\AppDomains.x64.mdmp )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %DUMPER% -a "%PROJECT_ROOT%\Source\Clr\LocalVariables\bin\Debug\net461\LocalVariables.exe" -d %PROJECT_ROOT%\Source\Clr\Framework.x64\LocalVariables.x64.mdmp )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %DUMPER% -a "%PROJECT_ROOT%\Source\Clr\NestedException\bin\Debug\net461\NestedException.exe" -d %PROJECT_ROOT%\Source\Clr\Framework.x64\NestedException.x64.mdmp )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %DUMPER% -a "%PROJECT_ROOT%\Source\Clr\Types\bin\Debug\net461\Types.exe" -d %PROJECT_ROOT%\Source\Clr\Framework.x64\Types.x64.mdmp )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( set COMPlus_BuildFlavor=svr )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %DUMPER% -a "%PROJECT_ROOT%\Source\Clr\AppDomains\bin\Debug\net461\AppDomains.exe" -d %PROJECT_ROOT%\Source\Clr\Framework.x64\AppDomains.x64.svr.mdmp )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %DUMPER% -a "%PROJECT_ROOT%\Source\Clr\LocalVariables\bin\Debug\net461\LocalVariables.exe" -d %PROJECT_ROOT%\Source\Clr\Framework.x64\LocalVariables.x64.svr.mdmp )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %DUMPER% -a "%PROJECT_ROOT%\Source\Clr\NestedException\bin\Debug\net461\NestedException.exe" -d %PROJECT_ROOT%\Source\Clr\Framework.x64\NestedException.x64.svr.mdmp )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %DUMPER% -a "%PROJECT_ROOT%\Source\Clr\Types\bin\Debug\net461\Types.exe" -d %PROJECT_ROOT%\Source\Clr\Framework.x64\Types.x64.svr.mdmp )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( set COMPlus_BuildFlavor= )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( 7z a %PROJECT_ROOT%\Clr.Windows.x64.zip %PROJECT_ROOT%\Source\Clr\Framework.x64\*.* )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( md %PROJECT_ROOT%\Source\Clr\Framework.x86 )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %CORFLAGS% %PROJECT_ROOT%\Source\Clr\AppDomains\bin\Debug\net461\AppDomains.exe /32Bit+ )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %CORFLAGS% %PROJECT_ROOT%\Source\Clr\LocalVariables\bin\Debug\net461\LocalVariables.exe /32Bit+ )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %CORFLAGS% %PROJECT_ROOT%\Source\Clr\NestedException\bin\Debug\net461\NestedException.exe /32Bit+ )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %CORFLAGS% %PROJECT_ROOT%\Source\Clr\Types\bin\Debug\net461\Types.exe /32Bit+ )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( copy %PROJECT_ROOT%\Source\Clr\AppDomains\bin\Debug\net461\AppDomains.* %PROJECT_ROOT%\Source\Clr\Framework.x86 )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( copy %PROJECT_ROOT%\Source\Clr\LocalVariables\bin\Debug\net461\LocalVariables.* %PROJECT_ROOT%\Source\Clr\Framework.x86 )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( copy %PROJECT_ROOT%\Source\Clr\NestedException\bin\Debug\net461\NestedException.* %PROJECT_ROOT%\Source\Clr\Framework.x86 )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( copy %PROJECT_ROOT%\Source\Clr\SharedLibrary\bin\Debug\netstandard2.0\SharedLibrary.* %PROJECT_ROOT%\Source\Clr\Framework.x86 )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( copy %PROJECT_ROOT%\Source\Clr\Types\bin\Debug\net461\Types.* %PROJECT_ROOT%\Source\Clr\Framework.x86 )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %DUMPER32% -a "%PROJECT_ROOT%\Source\Clr\AppDomains\bin\Debug\net461\AppDomains.exe" -d %PROJECT_ROOT%\Source\Clr\Framework.x86\AppDomains.x86.mdmp )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %DUMPER32% -a "%PROJECT_ROOT%\Source\Clr\LocalVariables\bin\Debug\net461\LocalVariables.exe" -d %PROJECT_ROOT%\Source\Clr\Framework.x86\LocalVariables.x86.mdmp )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %DUMPER32% -a "%PROJECT_ROOT%\Source\Clr\NestedException\bin\Debug\net461\NestedException.exe" -d %PROJECT_ROOT%\Source\Clr\Framework.x86\NestedException.x86.mdmp )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %DUMPER32% -a "%PROJECT_ROOT%\Source\Clr\Types\bin\Debug\net461\Types.exe" -d %PROJECT_ROOT%\Source\Clr\Framework.x86\Types.x86.mdmp )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( set COMPlus_BuildFlavor=svr )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %DUMPER32% -a "%PROJECT_ROOT%\Source\Clr\AppDomains\bin\Debug\net461\AppDomains.exe" -d %PROJECT_ROOT%\Source\Clr\Framework.x86\AppDomains.x86.svr.mdmp )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %DUMPER32% -a "%PROJECT_ROOT%\Source\Clr\LocalVariables\bin\Debug\net461\LocalVariables.exe" -d %PROJECT_ROOT%\Source\Clr\Framework.x86\LocalVariables.x86.svr.mdmp )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %DUMPER32% -a "%PROJECT_ROOT%\Source\Clr\NestedException\bin\Debug\net461\NestedException.exe" -d %PROJECT_ROOT%\Source\Clr\Framework.x86\NestedException.x86.svr.mdmp )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( %DUMPER32% -a "%PROJECT_ROOT%\Source\Clr\Types\bin\Debug\net461\Types.exe" -d %PROJECT_ROOT%\Source\Clr\Framework.x86\Types.x86.svr.mdmp )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( set COMPlus_BuildFlavor= )
  - cmd: IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( 7z a %PROJECT_ROOT%\Clr.Windows.x86.zip %PROJECT_ROOT%\Source\Clr\Framework.x86\*.* )
  - ps: |-
        pushd $env:PROJECT_ROOT
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;
        $webClient = New-Object System.Net.WebClient;
        $webClient.Credentials = new-object System.Net.NetworkCredential($env:ARTIFACTS_USERNAME, $env:ARTIFACTS_PASSWORD);
        if (Test-Path NativeDumpTest.mingw.zip) {
            $filename = "NativeDumpTest.mingw.zip";
            $url = "https://sharpdebug.jfrog.io/sharpdebug/generic-local/${env:DUMPS_VERSION}/${filename}?override=1";
            $webClient.UploadData($url, "PUT", [System.IO.File]::ReadAllBytes("${env:PROJECT_ROOT}\$filename"));
        }
        if (Test-Path NativeDumpTest.VS2013.zip) {
            $filename = "NativeDumpTest.VS2013.zip";
            $url = "https://sharpdebug.jfrog.io/sharpdebug/generic-local/${env:DUMPS_VERSION}/${filename}?override=1";
            $webClient.UploadData($url, "PUT", [System.IO.File]::ReadAllBytes("${env:PROJECT_ROOT}\$filename"));
        }
        if (Test-Path NativeDumpTest.VS2015.zip) {
            $filename = "NativeDumpTest.VS2015.zip";
            $url = "https://sharpdebug.jfrog.io/sharpdebug/generic-local/${env:DUMPS_VERSION}/${filename}?override=1";
            $webClient.UploadData($url, "PUT", [System.IO.File]::ReadAllBytes("${env:PROJECT_ROOT}\$filename"));
        }
        if (Test-Path NativeDumpTest.VS2017.zip) {
            $filename = "NativeDumpTest.VS2017.zip";
            $url = "https://sharpdebug.jfrog.io/sharpdebug/generic-local/${env:DUMPS_VERSION}/${filename}?override=1";
            $webClient.UploadData($url, "PUT", [System.IO.File]::ReadAllBytes("${env:PROJECT_ROOT}\$filename"));
        }
        if (Test-Path Cpp17.VS2017.zip) {
            $filename = "Cpp17.VS2017.zip";
            $url = "https://sharpdebug.jfrog.io/sharpdebug/generic-local/${env:DUMPS_VERSION}/${filename}?override=1";
            $webClient.UploadData($url, "PUT", [System.IO.File]::ReadAllBytes("${env:PROJECT_ROOT}\$filename"));
        }
        if (Test-Path Clr.Windows.Core.zip) {
            $filename = "Clr.Windows.Core.zip";
            $url = "https://sharpdebug.jfrog.io/sharpdebug/generic-local/${env:DUMPS_VERSION}/${filename}?override=1";
            $webClient.UploadData($url, "PUT", [System.IO.File]::ReadAllBytes("${env:PROJECT_ROOT}\$filename"));
        }
        if (Test-Path Clr.Windows.x64.zip) {
            $filename = "Clr.Windows.x64.zip";
            $url = "https://sharpdebug.jfrog.io/sharpdebug/generic-local/${env:DUMPS_VERSION}/${filename}?override=1";
            $webClient.UploadData($url, "PUT", [System.IO.File]::ReadAllBytes("${env:PROJECT_ROOT}\$filename"));
        }
        if (Test-Path Clr.Windows.x86.zip) {
            $filename = "Clr.Windows.x86.zip";
            $url = "https://sharpdebug.jfrog.io/sharpdebug/generic-local/${env:DUMPS_VERSION}/${filename}?override=1";
            $webClient.UploadData($url, "PUT", [System.IO.File]::ReadAllBytes("${env:PROJECT_ROOT}\$filename"));
        }

artifacts:
  - path: '**\bin\*.exe'
  - path: '**\bin\*.pdb'
  - path: '**\bin\*.*dmp'
  - path: '**\*.zip'
